## 00.PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cpu


## Introduction to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[1,2,3],
                        [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([4, 5, 6])

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [7,8,9],
                        [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 7,  8,  9],
         [16, 17, 18]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [16, 17, 18]])

### Random Tensors

In [16]:
# Create a random tensor of size (3,2)
random_tensor = torch.rand(3,2,8)
random_tensor

tensor([[[0.1482, 0.1033, 0.0041, 0.1277, 0.0766, 0.2526, 0.7760, 0.1253],
         [0.7163, 0.8393, 0.9079, 0.1104, 0.5283, 0.6655, 0.8208, 0.6017]],

        [[0.8233, 0.7741, 0.8968, 0.7382, 0.9888, 0.1432, 0.0931, 0.8335],
         [0.1679, 0.0140, 0.0445, 0.2843, 0.7824, 0.4201, 0.5661, 0.2293]],

        [[0.9590, 0.7293, 0.5472, 0.4050, 0.0529, 0.2825, 0.2264, 0.8348],
         [0.9973, 0.0917, 0.5848, 0.8963, 0.5383, 0.3642, 0.3217, 0.1799]]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [18]:
# For zeros tensor
zeros = torch.zeros(size=(8,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
# For ones tensor
ones = torch.ones(size=(3,3,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

### Creating a range of tensors and tensors-like

In [20]:
range_of_tensors = torch.arange(start=1, end=10, step=5)
range_of_tensors

tensor([1, 6])

In [21]:
# Creating tensors like
tensor_zero = torch.zeros_like(input=range_of_tensors)
tensor_zero

tensor([0, 0])

### Tensor Datatypes

In [22]:
# Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([1., 2., 3.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [25]:
int_64_tensor = torch.tensor([1,2,3])
int_64_tensor.dtype

torch.int64

In [26]:
float_32_tensor * int_64_tensor

tensor([1., 4., 9.])

### Getting information from tensors (attributes)

1. Tensor not right datatype -> for getting datatype `tensor.dtype`
2. Tensor not right shape -> for getting shape `tensor.shape`
3. Tensor not right device -> for getting device `tensor.device` 

In [27]:
# Create a tensor 
some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.0456, 0.0996, 0.0197, 0.3188],
        [0.9807, 0.8433, 0.9860, 0.6928]])

In [28]:
# Finding Details

print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.0456, 0.0996, 0.0197, 0.3188],
        [0.9807, 0.8433, 0.9860, 0.6928]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([2, 4])
Device tensor is stored on: cpu


### Tensor Operations

In [29]:
# Tensor addition 
tensor = torch.tensor([1,2,3])
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [30]:
# Tensor Multipliaction
tensor * 10 # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [31]:
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

In [32]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.matmul(tensor_A, tensor_B) this won't work because of shape mismatch 
# Reshaping the tensor by taking transpose

In [35]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [36]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding min, max, mean, sum, etc. (Tensor aggregation)

In [37]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [39]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [40]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [41]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [42]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
# Find the positional max and min
print(torch.argmax(x), torch.argmin(x))
print(x[9],x[0])

tensor(9) tensor(0)
tensor(90) tensor(0)


### Reshaping, Stacking, Squeezing, Unsqueezing 

In [44]:
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [46]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
z[:, 0] = 8
z, x

(tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
# Stack tensors vertically
x_stacked = torch.stack([x,x,x], dim=0)
x_stacked

tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [49]:
# Stack tensors horizontally
y = torch.stack([x,x,x], dim=1)
y

tensor([[8., 8., 8.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [50]:
# torch.squeeze() removes all the dimensions which have size 1

print(f"Before: {z}")
print(f"Before Shape: {z.shape}")

z_squeezed = z.squeeze()
print(f"\nAfter: {z_squeezed}")
print(f"After Shape: {z_squeezed.shape}")

Before: tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]])
Before Shape: torch.Size([1, 9])

After: tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.])
After Shape: torch.Size([9])


In [51]:
# torch.unsqueeze() adds a dimension of 1 to a tensor

print(f"Before: {z_squeezed}")
print(f"Before Shape: {z_squeezed.shape}")

z_unsqueezed = z_squeezed.unsqueeze(dim=0)
print(f"\nAfter: {z_unsqueezed}")
print(f"After Shape: {z_unsqueezed.shape}")

Before: tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.])
Before Shape: torch.Size([9])

After: tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]])
After Shape: torch.Size([1, 9])


In [52]:
# torch.permute() changes the order of the axes
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

x_permuted = x_original.permute(2,0,1) # [color_channels, height, width]

print(f"Original Shape: {x_original.shape}")
print(f"Permuted Shape: {x_permuted.shape}")

Original Shape: torch.Size([224, 224, 3])
Permuted Shape: torch.Size([3, 224, 224])


In [53]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (Selecting data from tensors)

In [54]:
# Create a tensor
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [56]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [57]:
x[:, 1, 1]

tensor([5])

### PyTorch Tensors & NumPy 

In [58]:
# Numpy arrays to tensors
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
# Tensors to numpy arrays
tensor = torch.ones(8)
numpy_tensors = tensor.numpy()
tensor, numpy_tensors

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [61]:
tensor = tensor + 1
tensor, numpy_tensors

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility 

In [62]:
torch.rand(3,3) #Everytime different

tensor([[0.7914, 0.0769, 0.5968],
        [0.3585, 0.9020, 0.0328],
        [0.0178, 0.4969, 0.9102]])

In [63]:
# Set seed for reproducibility
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
