## 00.PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cpu


## Introduction to Tensors

### Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[1,2,3],
                        [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([4, 5, 6])

In [12]:
MATRIX.shape

torch.Size([2, 3])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [7,8,9],
                        [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 7,  8,  9],
         [16, 17, 18]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [16, 17, 18]])

### Random Tensors

In [17]:
# Create a random tensor of size (3,2)
random_tensor = torch.rand(3,2,8)
random_tensor

tensor([[[0.7783, 0.0378, 0.4140, 0.4999, 0.1159, 0.1285, 0.1051, 0.9839],
         [0.8225, 0.2407, 0.3525, 0.4055, 0.0783, 0.9518, 0.8577, 0.9736]],

        [[0.7826, 0.2187, 0.4012, 0.3860, 0.5816, 0.7186, 0.7996, 0.5194],
         [0.1739, 0.8105, 0.9573, 0.2618, 0.4207, 0.8553, 0.2351, 0.5688]],

        [[0.4118, 0.8562, 0.2439, 0.5049, 0.5583, 0.6808, 0.4400, 0.1883],
         [0.4586, 0.6536, 0.8066, 0.1453, 0.2193, 0.6854, 0.3860, 0.3680]]])

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [19]:
# For zeros tensor
zeros = torch.zeros(size=(8,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [20]:
# For ones tensor
ones = torch.ones(size=(3,3,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

### Creating a range of tensors and tensors-like

In [21]:
range_of_tensors = torch.arange(start=1, end=10, step=5)
range_of_tensors

tensor([1, 6])

In [22]:
# Creating tensors like
tensor_zero = torch.zeros_like(input=range_of_tensors)
tensor_zero

tensor([0, 0])

### Tensor Datatypes

In [23]:
# Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([1., 2., 3.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [26]:
int_64_tensor = torch.tensor([1,2,3])
int_64_tensor.dtype

torch.int64

In [27]:
float_32_tensor * int_64_tensor

tensor([1., 4., 9.])

### Getting information from tensors (attributes)

1. Tensor not right datatype -> for getting datatype `tensor.dtype`
2. Tensor not right shape -> for getting shape `tensor.shape`
3. Tensor not right device -> for getting device `tensor.device` 

In [28]:
# Create a tensor 
some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.7210, 0.7220, 0.2361, 0.1203],
        [0.7333, 0.8136, 0.4279, 0.4678]])

In [29]:
# Finding Details

print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7210, 0.7220, 0.2361, 0.1203],
        [0.7333, 0.8136, 0.4279, 0.4678]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([2, 4])
Device tensor is stored on: cpu


### Tensor Operations

In [30]:
# Tensor addition 
tensor = torch.tensor([1,2,3])
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [31]:
# Tensor Multipliaction
tensor * 10 # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

In [33]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.matmul(tensor_A, tensor_B) this won't work because of shape mismatch 
# Reshaping the tensor by taking transpose

In [36]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [37]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding min, max, mean, sum, etc. (Tensor aggregation)

In [38]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [40]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [41]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [42]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [43]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
# Find the positional max and min
print(torch.argmax(x), torch.argmin(x))
print(x[9],x[0])

tensor(9) tensor(0)
tensor(90) tensor(0)


### Reshaping, Stacking, Squeezing, Unsqueezing 

In [45]:
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [47]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
z[:, 0] = 8
z, x

(tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [49]:
# Stack tensors vertically
x_stacked = torch.stack([x,x,x], dim=0)
x_stacked

tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
# Stack tensors horizontally
y = torch.stack([x,x,x], dim=1)
y

tensor([[8., 8., 8.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [51]:
# torch.squeeze() removes all the dimensions which have size 1

print(f"Before: {z}")
print(f"Before Shape: {z.shape}")

z_squeezed = z.squeeze()
print(f"\nAfter: {z_squeezed}")
print(f"After Shape: {z_squeezed.shape}")

Before: tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]])
Before Shape: torch.Size([1, 9])

After: tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.])
After Shape: torch.Size([9])


In [52]:
# torch.unsqueeze() adds a dimension of 1 to a tensor

print(f"Before: {z_squeezed}")
print(f"Before Shape: {z_squeezed.shape}")

z_unsqueezed = z_squeezed.unsqueeze(dim=0)
print(f"\nAfter: {z_unsqueezed}")
print(f"After Shape: {z_unsqueezed.shape}")

Before: tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.])
Before Shape: torch.Size([9])

After: tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]])
After Shape: torch.Size([1, 9])


In [53]:
# torch.permute() changes the order of the axes
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

x_permuted = x_original.permute(2,0,1) # [color_channels, height, width]

print(f"Original Shape: {x_original.shape}")
print(f"Permuted Shape: {x_permuted.shape}")

Original Shape: torch.Size([224, 224, 3])
Permuted Shape: torch.Size([3, 224, 224])


In [54]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (Selecting data from tensors)

In [56]:
# Create a tensor
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [60]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [61]:
x[:, 1, 1]

tensor([5])

### PyTorch Tensors & NumPy 

In [66]:
# Numpy arrays to tensors
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# Tensors to numpy arrays
tensor = torch.ones(8)
numpy_tensors = tensor.numpy()
tensor, numpy_tensors

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [70]:
tensor = tensor + 1
tensor, numpy_tensors

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility 

In [75]:
torch.rand(3,3) #Everytime different

tensor([[0.1673, 0.4612, 0.0792],
        [0.1675, 0.1740, 0.8940],
        [0.3053, 0.7493, 0.7428]])

In [77]:
# Set seed for reproducibility
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
